/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#006948",
        "primary-container": "#00855d",
        "on-primary": "#ffffff",
        "on-primary-container": "#f5fff7",
        "primary-fixed": "#85f8c4",
        "primary-fixed-dim": "#68dba9",
        "on-primary-fixed": "#002114",
        "on-primary-fixed-variant": "#005137",
        secondary: "#565e74",
        "secondary-container": "#dae2fd",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5c647a",
        tertiary: "#0051d5",
        "tertiary-container": "#316bf3",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fefcff",
        "tertiary-fixed": "#dbe1ff",
        "on-tertiary-fixed": "#00174b",
        "on-tertiary-fixed-variant": "#003ea8",
        "secondary-fixed": "#dae2fd",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary-fixed-dim": "#b4c5ff",
        "secondary-fixed-dim": "#bec6e0",
        inverse: {
          primary: "#68dba9",
          surface: "#213145",
          on: {
            surface: "#eaf1ff",
          },
        },
        surface: "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#3d4a42",
        outline: "#6d7a72",
        "outline-variant": "#bccac0",
        background: "#f8f9ff",
        "on-background": "#0b1c30",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        emerald: {
          50: "#f0fdfa",
          100: "#ccfbf1",
          200: "#99f6e4",
          300: "#5eead4",
          400: "#2dd4bf",
          500: "#14b8a6",
          600: "#0d9488",
          700: "#0f766e",
          800: "#02433f",
          900: "#022c2a",
        },
        red: {
          400: "#f87171",
          500: "#ef4444",
        },
        amber: {
          400: "#fbbf24",
        },
        slate: {
          300: "#cbd5e1",
          400: "#94a3b8",
          500: "#64748b",
          700: "#334155",
          800: "#1e293b",
          900: "#0f172a",
        },
      },
      borderRadius: {
        sm: "0.5rem",
        DEFAULT: "1rem",
        md: "0.75rem",
        lg: "2rem",
        xl: "3rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        "display-hero": ["var(--font-bricolage)", "sans-serif"],
        "body-sm": ["var(--font-hanken)", "sans-serif"],
        "body-xl": ["var(--font-hanken)", "sans-serif"],
        "headline-xl-mobile": ["var(--font-bricolage)", "sans-serif"],
        "headline-sm": ["var(--font-bricolage)", "sans-serif"],
        "body-md": ["var(--font-hanken)", "sans-serif"],
        "body-lg": ["var(--font-hanken)", "sans-serif"],
        "label-lg": ["var(--font-hanken)", "sans-serif"],
        "label-md": ["var(--font-hanken)", "sans-serif"],
        "label-sm": ["var(--font-hanken)", "sans-serif"],
        "headline-xl": ["var(--font-bricolage)", "sans-serif"],
        "display-hero-mobile": ["var(--font-bricolage)", "sans-serif"],
        "headline-md": ["var(--font-bricolage)", "sans-serif"],
        "headline-lg": ["var(--font-bricolage)", "sans-serif"],
        "code-badge": ["var(--font-hanken)", "monospace"],
        "body-sm": ["var(--font-hanken)", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-xl": ["20px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-xl-mobile": ["30px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "display-hero-mobile": ["38px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "800" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      spacing: {
        "space-xl": "3rem",
        "space-sm": "0.5rem",
        "margin-mobile": "1.25rem",
        "gutter-mobile": "1rem",
        "space-lg": "1.75rem",
        "margin": "3rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "gutter": "1.5rem",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgba(11, 28, 48, 0.05)",
        sm: "0 1px 3px 0 rgba(11, 28, 48, 0.08), 0 1px 2px 0 rgba(11, 28, 48, 0.04)",
        md: "0 4px 6px -1px rgba(11, 28, 48, 0.1), 0 2px 4px -1px rgba(11, 28, 48, 0.06)",
        lg: "0 10px 15px -3px rgba(11, 28, 48, 0.1), 0 4px 6px -2px rgba(11, 28, 48, 0.05)",
        xl: "0 20px 25px -5px rgba(11, 28, 48, 0.1), 0 10px 10px -5px rgba(11, 28, 48, 0.04)",
        "2xl": "0 25px 50px -12px rgba(11, 28, 48, 0.25)",
        "3xl": "0 50px 50px -50px rgba(0, 0, 0, 0.3)",
        "inner-sm": "inset 0 1px 2px 0 rgba(11, 28, 48, 0.06)",
        glow: "0 4px 14px rgba(0, 105, 72, 0.25)",
      },
      maxWidth: {
        "container-max": "1240px",
      },
      animation: {
        "pulse-dot": "pulse-dot 2s infinite",
        "pulse-ring": "pulse-ring 2s cubic-bezier(0.16, 1, 0.3, 1) infinite",
        "cursor-blink": "cursor-blink 0.8s step-end infinite",
        "bounce-slow": "bounce 5s infinite",
      },
      keyframes: {
        "pulse-dot": {
          "0%, 100%": { transform: "scale(1)", opacity: "1" },
          "50%": { transform: "scale(1.3)", opacity: "0.6" },
        },
        "pulse-ring": {
          "0%": { transform: "scale(0.9)", opacity: "0.8" },
          "80%": { transform: "scale(2.8)", opacity: "0" },
          "100%": { transform: "scale(2.8)", opacity: "0" },
        },
        "cursor-blink": {
          "from, to": { backgroundColor: "transparent" },
          "50%": { backgroundColor: "#3FB950" },
        },
      },
    },
  },
  plugins: [],
};
