export interface Project {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  impact: string;
  tags: string[];
  budget: string;
  weeks: string;
  industry: string;
  budgetTier: "tier-entry" | "tier-core" | "tier-enterprise";
  appType: "web" | "mobile" | "portal" | "ecommerce" | "data";
  stack: string;
  keywords: string;
  image: string;
  imageAlt: string;
  icon: string;
}

export interface SpotlightCase {
  id: string;
  title: string;
  description: string;
  impact: string;
  price: string;
  weeks: string;
  industry: string;
  image: string;
  imageAlt: string;
  icon: string;
  tags: string[];
}

export const spotlightCases: SpotlightCase[] = [
  {
    id: "omnihub",
    title: "OmniHub Warehouse Scanner",
    description:
      "Ruggedized, offline-first mobile inventory tracking system with sub-second Honeywell barcode ingestion and bi-directional ERP sync across 6 distribution hubs.",
    impact: "94% faster cycle counts & zero lost shipments",
    price: "$48,000",
    weeks: "8 Weeks",
    industry: "Logistics & Supply Chain",
    image:
      "https://lh3.googleusercontent.com/aida/AEtjO1X5RyMhgmUvtXsQRZwgrC8bjOoJaer29-pBa0bFSfp99Zvq6vOR2-ZPq0QmhSf_ptjTT_VYfW23gY17LfsT2NIOnc9eTXsstyFuI4C8AG-foXIP7zOMoXuiOQcH11XNgvuVdgyqaH3IQeJ9pquECxUR0OhW0LW-VAnM8phEnYGbP-T2MHk8yLmVTgeFYAp36Kn7rxZDgdeMIec10s2A-agwwHFPlKprOJTAm6UYstVCXg_iXwaX1I99cQ",
    imageAlt: "OmniHub Mobile Scanner App",
    icon: "qr_code_scanner",
    tags: ["React Native", "SQLite", "Node.js", "Honeywell SDK"],
  },
  {
    id: "carepoint",
    title: "CarePoint Clinical Intranet",
    description:
      "HIPAA-compliant medical knowledge and triage portal unifying document compliance, shifts, and EHR lookup protocols for 850+ active healthcare specialists.",
    impact: "Replaced 4 legacy servers; 100% audit pass",
    price: "$42,000",
    weeks: "6 Weeks",
    industry: "Healthcare & MedTech",
    image:
      "https://lh3.googleusercontent.com/aida/AEtjO1Ubx_oUk0ju69N6XcU3NZsl7AitkzHxk8kgCDJry2POQG98lHtJ0JnbDovI4OlqnkejdcVDeKdLhQ3df56rqxeJ4vHJ-7amX9rh9ToaxnjRxAJj2B9zuOk9GD64eG-ay9AooAqUVpM5K33eKtuluxsGGdjdh1jEoYcYxXgk5nhDgCrV3v8O88Jgsbf4SDMLjenk0dHVRor2ycAOzQzWqoUeMzUXlZ0sd-7Sq0RvEWHsAOsmP5j636o99QE",
    imageAlt: "CarePoint Healthcare Intranet",
    icon: "local_hospital",
    tags: ["SharePoint Online", "Azure AD SSO", "Power Automate", "HIPAA"],
  },
  {
    id: "aura-luxe",
    title: "Aura Luxe VIP Storefront",
    description:
      "Ultra-fast headless mobile commerce application featuring one-tap Apple Pay checkouts, personalized drop alerts, and dynamic product recommendations.",
    impact: "+38% repeat buyer rate & 3.1x mobile conversion",
    price: "$36,000",
    weeks: "6 Weeks",
    industry: "D2C & E-Commerce",
    image:
      "https://lh3.googleusercontent.com/aida/AEtjO1VQjQH3PV6eyxMTxuTqee80gbk5mmdpBowDQ7eAz9Y_MPpIGVwIK7dBsW1WBB9BWMzv0Uawsjhb3rqSyv-JAofVaxxai4i9Q3ylCQoJI4NJbWa7r3chgVgNK0bzpFVivkW89haaCdDUnpKdPPYM7gqUABzE5aliRoZFynd7NsKw2CYnn3UxOl4mkubDSk7nNflEKxtCDm1FHmg2JRRl2_i_Pqt8AXp6BwChFgNQuz8epRhh1yBIyQOFyN4",
    imageAlt: "Aura Luxe Mobile Commerce",
    icon: "shopping_bag",
    tags: ["Flutter", "Shopify API", "Klaviyo SDK", "Stripe"],
  },
];

export const projects: Project[] = [
  // Healthcare (6)
  {
    id: "carepoint",
    title: "CarePoint Patient Portal & Intranet",
    subtitle: "Patient Document Hub",
    description:
      "Consolidated clinical intranet and patient document hub unifying 850 medical staff with role-based HIPAA record lookups and Azure AD encryption.",
    impact: "70% faster chart retrieval • 100% HIPAA audit pass",
    tags: ["SharePoint", "Azure AD", "PowerAutomate"],
    budget: "$42,000",
    weeks: "6 Wks",
    industry: "healthcare",
    budgetTier: "tier-core",
    appType: "portal",
    stack: "portal-stack",
    keywords: "carepoint hipaa patient portal intranet sharepoint azure medical health",
    image: "https://lh3.googleusercontent.com/aida/AEtjO1Ubx_oUk0ju69N6XcU3NZsl7AitkzHxk8kgCDJry2POQG98lHtJ0JnbDovI4OlqnkejdcVDeKdLhQ3df56rqxeJ4vHJ-7amX9rh9ToaxnjRxAJj2B9zuOk9GD64eG-ay9AooAqUVpM5K33eKtuluxsGGdjdh1jEoYcYxXgk5nhDgCrV3v8O88Jgsbf4SDMLjenk0dHVRor2ycAOzQzWqoUeMzUXlZ0sd-7Sq0RvEWHsAOsmP5j636o99QE",
    imageAlt: "CarePoint Healthcare Portal",
    icon: "verified_user",
  },
  {
    id: "medschedule",
    title: "MedSchedule Telehealth Booking",
    subtitle: "Web Telehealth",
    description:
      "Self-service specialist scheduling with embedded Twilio WebRTC video rooms, automated SMS reminders, and zero double-booking locks.",
    impact: "-42% appointment no-shows • 14,000+ sessions held",
    tags: ["Next.js", "Twilio WebRTC", "Stripe Health"],
    budget: "$34,000",
    weeks: "5 Wks",
    industry: "healthcare",
    budgetTier: "tier-entry",
    appType: "web",
    stack: "react",
    keywords: "medschedule telehealth booking twilio web app calendar clinic video",
    image: "",
    imageAlt: "MedSchedule Telehealth App",
    icon: "trending_down",
  },
  {
    id: "orthotrack",
    title: "OrthoTrack Physical Therapy App",
    subtitle: "Mobile App (iOS/And)",
    description:
      "Patient exercise adherence mobile application featuring camera posture detection and daily range-of-motion logging for physical rehabilitation clinics.",
    impact: "89% protocol completion rate • 4.8 App Store score",
    tags: ["Flutter", "CoreML", "Firebase"],
    budget: "$28,000",
    weeks: "4 Wks",
    industry: "healthcare",
    budgetTier: "tier-entry",
    appType: "mobile",
    stack: "mobile-stack",
    keywords: "orthotrack physical therapy mobile flutter camera motion rehabilitation",
    image: "",
    imageAlt: "OrthoTrack Mobile App",
    icon: "check_circle",
  },
  {
    id: "biolab",
    title: "BioLab Sample Tracking LIMS",
    subtitle: "Laboratory LIMS",
    description:
      "Full-lifecycle biospecimen inventory tracker with cryogenic freezer rack visualization, barcode scanning, and FDA 21 CFR Part 11 audit trails.",
    impact: "220k specimens managed • Zero custody breaks",
    tags: ["FastAPI", "React", "PostgreSQL"],
    budget: "$58,000",
    weeks: "8 Wks",
    industry: "healthcare",
    budgetTier: "tier-core",
    appType: "web",
    stack: "backend",
    keywords: "biolab lims laboratory sample tracking biotech python postgres",
    image: "",
    imageAlt: "BioLab LIMS",
    icon: "speed",
  },
  {
    id: "dentalcare",
    title: "DentalCare Multi-Clinic EHR Sync",
    subtitle: "EHR Integration",
    description:
      "Bi-directional synchronization layer joining 8 satellite dental practices to a unified central billing, scheduling, and x-ray imaging repository.",
    impact: "Saved 18 hours/week in duplicate billing data entry",
    tags: ["Node.js", "HL7 / FHIR", "AWS Lambda"],
    budget: "$36,000",
    weeks: "5 Wks",
    industry: "healthcare",
    budgetTier: "tier-core",
    appType: "portal",
    stack: "react",
    keywords: "dentalcare ehr sync dental patient records multi location",
    image: "",
    imageAlt: "DentalCare EHR Sync",
    icon: "savings",
  },
  {
    id: "pharmadose",
    title: "PharmaDose Prescription Verifier",
    subtitle: "Clinical Decision Web",
    description:
      "Safety validation engine that cross-references dosages against patient kidney markers and FDA adverse-interaction matrices prior to pharmacy dispense.",
    impact: "Prevented 34 critical drug-interaction collisions",
    tags: ["React", "Python", "Redis Cache"],
    budget: "$48,000",
    weeks: "7 Wks",
    industry: "healthcare",
    budgetTier: "tier-core",
    appType: "web",
    stack: "react",
    keywords: "pharmadose prescription verifier pharmacist drug interaction pharmacy",
    image: "",
    imageAlt: "PharmaDose Verifier",
    icon: "security",
  },
  // Logistics (7)
  {
    id: "freightflow",
    title: "FreightFlow Dispatch & Telemetry",
    subtitle: "Fleet Telemetry Web",
    description:
      "Live interactive GPS telemetry and load assignment console handling 400 semi-trucks, driver hours-of-service compliance, and fuel efficiency scoring.",
    impact: "12% fleet fuel savings • Sub-second position ping",
    tags: ["React / Mapbox", "Go Kafka", "TimescaleDB"],
    budget: "$62,000",
    weeks: "9 Wks",
    industry: "logistics",
    budgetTier: "tier-enterprise",
    appType: "web",
    stack: "react",
    keywords: "freightflow fleet dispatch telemetry trucking logistics gps map",
    image: "",
    imageAlt: "FreightFlow Telemetry",
    icon: "local_gas_station",
  },
  {
    id: "coldchain",
    title: "ColdChain Temperature IoT Portal",
    subtitle: "IoT Data Portal",
    description:
      "Real-time thermal sensor alert network tracking perishable food and vaccine cargo with automated incident logging and SMS threshold excursions.",
    impact: "Zero spoilage write-offs across 1,800 shipments",
    tags: ["Node.js", "AWS IoT Core", "React Dashboard"],
    budget: "$44,000",
    weeks: "6 Wks",
    industry: "logistics",
    budgetTier: "tier-core",
    appType: "data",
    stack: "backend",
    keywords: "coldchain temperature iot sensor reefer food pharma logistics",
    image: "",
    imageAlt: "ColdChain IoT Portal",
    icon: "thermostat",
  },
  {
    id: "dockmaster",
    title: "DockMaster 3PL Dock Scheduler",
    subtitle: "3PL Dock Web",
    description:
      "Carrier-facing dock door booking application eliminating truck yard congestion with time-slotted check-ins and live gate camera verification.",
    impact: "Yard wait times cut from 3.8 hrs to 26 mins",
    tags: ["Next.js", "Tailwind", "Supabase"],
    budget: "$32,000",
    weeks: "5 Wks",
    industry: "logistics",
    budgetTier: "tier-entry",
    appType: "web",
    stack: "react",
    keywords: "dockmaster warehouse dock scheduler carrier booking 3pl logistics",
    image: "",
    imageAlt: "DockMaster Scheduler",
    icon: "schedule",
  },
  {
    id: "routewise",
    title: "RouteWise Last-Mile Driver App",
    subtitle: "Driver Mobile",
    description:
      "Multi-stop route sequence optimizer with instant electronic proof-of-delivery (e-sign + photo capture) and customer delivery ETA updates.",
    impact: "+22% stops per shift • 100% digital POD",
    tags: ["Flutter", "Mapbox Turn-by-Turn", "S3 Media"],
    budget: "$38,000",
    weeks: "6 Wks",
    industry: "logistics",
    budgetTier: "tier-core",
    appType: "mobile",
    stack: "mobile-stack",
    keywords: "routewise last mile navigation proof of delivery signature mobile flutter",
    image: "",
    imageAlt: "RouteWise Driver App",
    icon: "navigation",
  },
  {
    id: "pallettrack",
    title: "PalletTrack RFID Ingestion Engine",
    subtitle: "RFID Engine",
    description:
      "Ultra-high throughput gateway daemon capturing up to 600 passive RFID pallet tags simultaneously passing through high-speed warehouse portal docks.",
    impact: "Sub-20ms packet parsing • Zero tag collision drop",
    tags: ["Go / MQTT", "PostgreSQL", "Impinj Reader SDK"],
    budget: "$54,000",
    weeks: "7 Wks",
    industry: "logistics",
    budgetTier: "tier-core",
    appType: "data",
    stack: "backend",
    keywords: "pallettrack rfid ingestion engine warehouse logistics bulk items",
    image: "",
    imageAlt: "PalletTrack RFID Engine",
    icon: "sensors",
  },
  {
    id: "customsclear",
    title: "CustomsClear Cross-Border Vault",
    subtitle: "Document Vault",
    description:
      "Automated commercial invoice and bill-of-lading processing engine with AI-assisted tariff classification for US-Canada freight brokers.",
    impact: "Border clearance delay reduced by 78%",
    tags: ["React", "Python OCR", "PostgreSQL"],
    budget: "$29,000",
    weeks: "4 Wks",
    industry: "logistics",
    budgetTier: "tier-entry",
    appType: "portal",
    stack: "react",
    keywords: "customsclear customs cross border document vault freight brokerage ocr",
    image: "",
    imageAlt: "CustomsClear Vault",
    icon: "verified",
  },
  // E-Commerce (8)
  {
    id: "aura-luxe-mobile",
    title: "Aura Luxe Headless Mobile Store",
    subtitle: "Headless Mobile App",
    description:
      "Direct-to-consumer luxury apparel app powered by Shopify Headless Storefront API, offering sub-16ms transitions and 1-tap Apple Pay checkouts.",
    impact: "+38% repeat buyer rate • 3.1x mobile conversion",
    tags: ["Flutter", "Shopify API", "Klaviyo"],
    budget: "$36,000",
    weeks: "6 Wks",
    industry: "ecommerce",
    budgetTier: "tier-core",
    appType: "ecommerce",
    stack: "mobile-stack",
    keywords: "aura luxe shopify headless mobile store apparel fashion flutter",
    image: "",
    imageAlt: "Aura Luxe Mobile Store",
    icon: "shopping_cart",
  },
  {
    id: "bulcagear",
    title: "BulkGear OpenCart B2B Wholesale",
    subtitle: "B2B Wholesale Portal",
    description:
      "Heavy equipment distributor portal with tiered account volume pricing, custom net-30 terms invoicing, and CSV bulk reorder intake.",
    impact: "$4.2M in annual B2B gross order volume processed",
    tags: ["OpenCart Modern", "PHP 8.2", "QuickBooks Sync"],
    budget: "$48,000",
    weeks: "7 Wks",
    industry: "ecommerce",
    budgetTier: "tier-core",
    appType: "ecommerce",
    stack: "ecommerce-stack",
    keywords: "bulkgear opencart wholesale b2b tier pricing distributor ecommerce",
    image: "",
    imageAlt: "BulkGear Wholesale",
    icon: "payments",
  },
  {
    id: "moduliving",
    title: "ModuLiving 3D Modular Configurator",
    subtitle: "3D WebGL Configurator",
    description:
      "Interactive Three.js modular sectional furniture designer calculating real-time pricing and generating dynamic BOM schematics for factory cuts.",
    impact: "+44% Average Order Value ($3,850 avg)",
    tags: ["Three.js", "React Three Fiber", "Shopify Storefront"],
    budget: "$52,000",
    weeks: "8 Wks",
    industry: "ecommerce",
    budgetTier: "tier-core",
    appType: "ecommerce",
    stack: "react",
    keywords: "moduliving 3d configurator furniture threejs webgl customizer ecommerce",
    image: "",
    imageAlt: "ModuLiving Configurator",
    icon: "view_in_ar",
  },
  {
    id: "subbox",
    title: "SubBox Subscription Engine",
    subtitle: "Subscription Engine",
    description:
      "Flexible recurring order engine with custom build-a-box curation, intelligent pause/skip flows, and automated smart dunning to recover failed cards.",
    impact: "-28% subscriber churn • $65k MRR recovered",
    tags: ["Shopify Subscriptions", "Node.js", "Stripe Billing"],
    budget: "$34,000",
    weeks: "5 Wks",
    industry: "ecommerce",
    budgetTier: "tier-entry",
    appType: "ecommerce",
    stack: "ecommerce-stack",
    keywords: "subbox subscription commerce billing churn stripe ecommerce",
    image: "",
    imageAlt: "SubBox Engine",
    icon: "autorenew",
  },
  {
    id: "quickdrops",
    title: "QuickDrops Flash-Sale Checkout",
    subtitle: "High-Concurrency Queue",
    description:
      "Virtual waiting room and bot-resistant checkout pipeline handling sudden bursts of 25,000 concurrent sneaker buyers without storefront downtime.",
    impact: "Handled 18k orders in 4 minutes with 0 crashes",
    tags: ["Go Lang", "Redis Queue", "Cloudflare Workers"],
    budget: "$42,000",
    weeks: "6 Wks",
    industry: "ecommerce",
    budgetTier: "tier-core",
    appType: "ecommerce",
    stack: "backend",
    keywords: "quickdrops flash sale checkout queue high traffic scale drops",
    image: "",
    imageAlt: "QuickDrops Checkout",
    icon: "flash_on",
  },
  {
    id: "vendorlink",
    title: "VendorLink Multi-Vendor Backend",
    subtitle: "Marketplace Platform",
    description:
      "Curated artisan food marketplace orchestrating vendor catalog self-onboarding, split automated payments, and multi-origin shipping rate calculations.",
    impact: "120 onboarded vendors • $1.8M GMV in 6 months",
    tags: ["Next.js", "Stripe Connect", "PostgreSQL"],
    budget: "$68,000",
    weeks: "10 Wks",
    industry: "ecommerce",
    budgetTier: "tier-enterprise",
    appType: "ecommerce",
    stack: "react",
    keywords: "vendorlink marketplace vendor portal payouts commission multi merchant",
    image: "",
    imageAlt: "VendorLink Marketplace",
    icon: "store",
  },
  // FinTech (5)
  {
    id: "apexledger",
    title: "ApexLedger Multi-Entity Reconciliation",
    subtitle: "Reconciliation Engine",
    description:
      "Automated transaction reconciliation suite matching bank feeds across 12 legal corporate entities with QuickBooks and NetSuite GL accounts.",
    impact: "Month-end close time reduced from 9 days to 4 hours",
    tags: ["Python", "Plaid API", "Postgres"],
    budget: "$56,000",
    weeks: "8 Wks",
    industry: "fintech",
    budgetTier: "tier-core",
    appType: "data",
    stack: "backend",
    keywords: "apexledger financial reconciliation plaid quickbooks multi entity accounting fintech",
    image: "",
    imageAlt: "ApexLedger Engine",
    icon: "account_balance",
  },
  {
    id: "paystream",
    title: "PayStream Custom ACH Payout Engine",
    subtitle: "Disbursement Web",
    description:
      "Compliant batch contractor disbursement system with W-9 automated collection, IRS 1099-NEC digital generation, and Next-Day ACH origination.",
    impact: "$12M in payout disbursements executed without fraud",
    tags: ["React", "Stripe Treasury", "Node.js"],
    budget: "$38,000",
    weeks: "6 Wks",
    industry: "fintech",
    budgetTier: "tier-core",
    appType: "web",
    stack: "react",
    keywords: "paystream ach stripe payout contractor payments fintech",
    image: "",
    imageAlt: "PayStream Engine",
    icon: "credit_card",
  },
  {
    id: "microlend",
    title: "MicroLend Small Business Loan Portal",
    subtitle: "Underwriting Portal",
    description:
      "Intelligent CDFI borrower intake application featuring Experian business credit bureau pulls, cash-flow scoring, and instant loan covenant generation.",
    impact: "Underwriting turnaround dropped from 14 days to 48 hrs",
    tags: ["Next.js", "Python Underwriting", "DocuSign API"],
    budget: "$64,000",
    weeks: "9 Wks",
    industry: "fintech",
    budgetTier: "tier-enterprise",
    appType: "portal",
    stack: "react",
    keywords: "microlend loan application underwriting small business credit fintech",
    image: "",
    imageAlt: "MicroLend Portal",
    icon: "verified",
  },
  {
    id: "captable",
    title: "CapTable Investor Relations Dashboard",
    subtitle: "Investor Portal",
    description:
      "Secure investor reporting room and stock option ledger for growth-stage startups, showing round dilution modeling and financial quarterly updates.",
    impact: "$85M in capital ownership visualized cleanly",
    tags: ["React", "Tailwind", "Supabase Auth"],
    budget: "$32,000",
    weeks: "5 Wks",
    industry: "fintech",
    budgetTier: "tier-entry",
    appType: "web",
    stack: "react",
    keywords: "captable investor relations equity options shares startup dashboard",
    image: "",
    imageAlt: "CapTable Dashboard",
    icon: "pie_chart",
  },
  // Manufacturing & Field Ops (6)
  {
    id: "shopfloor",
    title: "ShopFloor CNC Monitoring Dashboard",
    subtitle: "OEE Factory Dashboard",
    description:
      "Live Overall Equipment Effectiveness (OEE) tracking console connected directly to 28 Haas CNC milling machines via MTConnect protocol.",
    impact: "+19% plant spindle uptime • 30s alert response",
    tags: ["React", "MTConnect / MQTT", "InfluxDB"],
    budget: "$52,000",
    weeks: "7 Wks",
    industry: "manufacturing",
    budgetTier: "tier-core",
    appType: "data",
    stack: "react",
    keywords: "shopfloor cnc oee dashboard telemetry manufacturing factory",
    image: "",
    imageAlt: "ShopFloor CNC Monitor",
    icon: "precision_manufacturing",
  },
  {
    id: "fieldpro",
    title: "FieldPro HVAC Dispatch & Invoicing",
    subtitle: "Mobile Field Service",
    description:
      "Offline mobile work-order app for 45 service technicians with inventory truck checkouts, photo diagnostics, and on-site Stripe invoice payment collection.",
    impact: "Same-day payment collected on 91% of service calls",
    tags: ["React Native", "WatermelonDB", "Stripe Terminal"],
    budget: "$54,000",
    weeks: "7 Wks",
    industry: "manufacturing",
    budgetTier: "tier-core",
    appType: "mobile",
    stack: "mobile-stack",
    keywords: "fieldpro hvac technician dispatch invoice offline mobile field ops",
    image: "",
    imageAlt: "FieldPro HVAC Dispatch",
    icon: "build",
  },
  {
    id: "safetyaudit",
    title: "SafetyAudit OSHA Mobile Checklist",
    subtitle: "Safety Inspection App",
    description:
      "Facility safety inspection application allowing plant managers to perform scheduled safety rounds, flag hazards, and generate PDF incident dockets.",
    impact: "100% on-time OSHA monthly compliance audits",
    tags: ["Flutter", "SQLite", "PDF Generation"],
    budget: "$28,000",
    weeks: "4 Wks",
    industry: "manufacturing",
    budgetTier: "tier-entry",
    appType: "mobile",
    stack: "mobile-stack",
    keywords: "safetyaudit osha compliance checklist incident mobile inspection",
    image: "",
    imageAlt: "SafetyAudit Checklist",
    icon: "health_and_safety",
  },
  // Hospitality (3)
  {
    id: "propmaster",
    title: "PropMaster Tenant & Maintenance Portal",
    subtitle: "Tenant Portal",
    description:
      "Residential portal managing 1,200 apartment units for automated ACH rent collection, lease renewal e-signing, and maintenance ticket tracking.",
    impact: "97% of rent collected by 2nd of each month",
    tags: ["React", "Stripe ACH", "PostgreSQL"],
    budget: "$38,000",
    weeks: "6 Wks",
    industry: "hospitality",
    budgetTier: "tier-core",
    appType: "portal",
    stack: "react",
    keywords: "propmaster tenant portal maintenance rent pay real estate hospitality",
    image: "",
    imageAlt: "PropMaster Tenant Hub",
    icon: "apartment",
  },
  {
    id: "venuebooker",
    title: "VenueBooker Event Space Booking",
    subtitle: "Event Scheduler",
    description:
      "Interactive multi-room floor plan reservation tool with catering add-ons, calendar sync, and deposit lockouts for boutique event venues.",
    impact: "+34% weekday room utilization",
    tags: ["Next.js", "Tailwind", "Stripe API"],
    budget: "$32,000",
    weeks: "5 Wks",
    industry: "hospitality",
    budgetTier: "tier-entry",
    appType: "web",
    stack: "react",
    keywords: "venuebooker event space scheduler wedding booking hospitality",
    image: "",
    imageAlt: "VenueBooker Scheduler",
    icon: "celebration",
  },
];

export const industries = [
  { id: "all", label: "All Industries", count: 40 },
  { id: "healthcare", label: "Healthcare & MedTech", count: 6 },
  { id: "logistics", label: "Logistics & Supply Chain", count: 7 },
  { id: "ecommerce", label: "E-Commerce & Retail", count: 8 },
  { id: "fintech", label: "FinTech & Financial", count: 5 },
  { id: "manufacturing", label: "Manufacturing & Field Ops", count: 6 },
  { id: "saas", label: "B2B SaaS & Services", count: 5 },
  { id: "hospitality", label: "Hospitality & Real Estate", count: 3 },
];

export const typeOptions = [
  { value: "all", label: "Architecture: All Types" },
  { value: "web", label: "Custom Web App" },
  { value: "mobile", label: "Mobile (iOS / Android)" },
  { value: "portal", label: "Enterprise Portal / CMS" },
  { value: "ecommerce", label: "E-Commerce Architecture" },
  { value: "data", label: "BI & Modern Data Engine" },
];

export const budgetOptions = [
  { value: "all", label: "Budget: All Tiers ($20k–$95k)" },
  { value: "tier-entry", label: "Under $35,000 (Rapid Sprint)" },
  { value: "tier-core", label: "$35,000 – $60,000 (Production Scale)" },
  { value: "tier-enterprise", label: "$60,000 – $95,000 (Flagship Ecosystem)" },
];

export const stackOptions = [
  { value: "all", label: "Primary Tech Stack: All" },
  { value: "react", label: "React / Next.js" },
  { value: "mobile-stack", label: "React Native / Flutter" },
  { value: "backend", label: "Node / Python / Go" },
  { value: "ecommerce-stack", label: "Shopify / OpenCart" },
  { value: "portal-stack", label: "SharePoint / Azure" },
];
